### ISSUE TITLE
Error report with Simple Sidearms when a tool deteriorated to ash

### ISSUE THREAD

**Issue by ZXfkSIE** [LecrisUT/Rimworld-SurvivalTools#11]
How to reproduce:
1. equip a tool
2. use it in order to deteriorate its HP to 0
3. see log window

https://gist.github.com/02e1d7982b843c7be0574be5173d9d4d

**Comment by LecrisUT** [comment]
Is the log truncated? Try uploading on other gist like websites like pastebin.com

**Comment by ZXfkSIE** [comment]
> Is the log truncated? Try uploading on other gist like websites like pastebin.com

I do not think it was truncated. BTW, I tried uploading again and pasted the link.
