### ISSUE TITLE
Spiking GetStatValueJob method (probably GetStatValueJob_Fallback is the culprit)

### ISSUE THREAD

**Issue by Taranchuk** [LecrisUT/Rimworld-SurvivalTools#5]
https://media.discordapp.net/attachments/701640918113058846/755202183334723595/unknown.png

**Comment by LecrisUT** [comment]
I tried to implement a rolling Stat dictionary buffer, but it's not worth the complications of having to clear the buffer every few ticks or finding any possible things that affect the stat to refresh it.
If the `GetComp` can fix it than this should do it:  LecrisUT/Rimworld-ToolsFramework@70439af
